name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  # to fetch code (actions/checkout)
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'TS-Check Source: node-18, ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set node version to 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build
